export interface Country {
  code: string;
  name: string;
}

// Qatar and GCC first, then major expat nationalities in Qatar, then alphabetical rest
// Codes are Pyronis Nationality CodeSystem: https://fhir.pyronis.health/CodeSystem/Nationality
export const COUNTRIES: Country[] = [
  { code: "634", name: "Qatar" },
  { code: "682", name: "Saudi Arabia" },
  { code: "784", name: "United Arab Emirates" },
  { code: "414", name: "Kuwait" },
  { code: "048", name: "Bahrain" },
  { code: "512", name: "Oman" },
  // Major expat nationalities in Qatar
  { code: "356", name: "India" },
  { code: "586", name: "Pakistan" },
  { code: "524", name: "Nepal" },
  { code: "050", name: "Bangladesh" },
  { code: "608", name: "Philippines" },
  { code: "818", name: "Egypt" },
  { code: "400", name: "Jordan" },
  { code: "422", name: "Lebanon" },
  { code: "760", name: "Syria" },
  { code: "736", name: "Sudan" },
  { code: "230", name: "Ethiopia" },
  { code: "826", name: "United Kingdom" },
  { code: "840", name: "United States of America" },
  // Rest alphabetical
  { code: "004", name: "Afghanistan" },
  { code: "248", name: "Aland Islands" },
  { code: "008", name: "Albania" },
  { code: "012", name: "Algeria" },
  { code: "016", name: "American Samoa" },
  { code: "020", name: "Andorra" },
  { code: "024", name: "Angola" },
  { code: "660", name: "Anguilla" },
  { code: "028", name: "Antigua and Barbuda" },
  { code: "032", name: "Argentina" },
  { code: "051", name: "Armenia" },
  { code: "533", name: "Aruba" },
  { code: "036", name: "Australia" },
  { code: "040", name: "Austria" },
  { code: "031", name: "Azerbaijan" },
  { code: "044", name: "Bahamas" },
  { code: "052", name: "Barbados" },
  { code: "112", name: "Belarus" },
  { code: "056", name: "Belgium" },
  { code: "084", name: "Belize" },
  { code: "204", name: "Benin" },
  { code: "060", name: "Bermuda" },
  { code: "064", name: "Bhutan" },
  { code: "068", name: "Bolivia" },
  { code: "544", name: "Bosnia and Herzegovina" },
  { code: "072", name: "Botswana" },
  { code: "074", name: "Bouvet Island" },
  { code: "076", name: "Brazil" },
  { code: "086", name: "British Indian Ocean" },
  { code: "096", name: "Brunei Darussalam" },
  { code: "100", name: "Bulgaria" },
  { code: "854", name: "Burkina Faso" },
  { code: "108", name: "Burundi" },
  { code: "132", name: "Cabo Verde" },
  { code: "116", name: "Cambodia" },
  { code: "120", name: "Cameroon" },
  { code: "124", name: "Canada" },
  { code: "136", name: "Cayman Islands" },
  { code: "140", name: "Central African Republic" },
  { code: "148", name: "Chad" },
  { code: "830", name: "Channel Islands" },
  { code: "152", name: "Chile" },
  { code: "156", name: "China" },
  { code: "162", name: "Christmas Island" },
  { code: "166", name: "Cocos Keeling Islands" },
  { code: "170", name: "Colombia" },
  { code: "174", name: "Comoros" },
  { code: "178", name: "Congo" },
  { code: "184", name: "Cook Islands" },
  { code: "188", name: "Costa Rica" },
  { code: "384", name: "Cote D'Ivoire" },
  { code: "191", name: "Croatia" },
  { code: "192", name: "Cuba" },
  { code: "531", name: "Curacao" },
  { code: "196", name: "Cyprus" },
  { code: "200", name: "Czechia" },
  { code: "180", name: "Democratic Congo" },
  { code: "208", name: "Denmark" },
  { code: "262", name: "Djibouti" },
  { code: "212", name: "Dominica" },
  { code: "214", name: "Dominican Republic" },
  { code: "218", name: "Ecuador" },
  { code: "222", name: "El Salvador" },
  { code: "226", name: "Equatorial Guinea" },
  { code: "080", name: "Eritrea" },
  { code: "233", name: "Estonia" },
  { code: "748", name: "Eswatini" },
  { code: "238", name: "Falkland Islands" },
  { code: "234", name: "Faroe Islands" },
  { code: "242", name: "Fiji" },
  { code: "246", name: "Finland" },
  { code: "250", name: "France" },
  { code: "254", name: "French Guiana" },
  { code: "258", name: "French Polynesia" },
  { code: "266", name: "Gabon" },
  { code: "270", name: "Gambia" },
  { code: "268", name: "Georgia" },
  { code: "280", name: "Germany" },
  { code: "288", name: "Ghana" },
  { code: "292", name: "Gibraltar" },
  { code: "300", name: "Greece" },
  { code: "304", name: "Greenland" },
  { code: "308", name: "Grenada" },
  { code: "312", name: "Guadeloupe" },
  { code: "316", name: "Guam" },
  { code: "320", name: "Guatemala" },
  { code: "831", name: "Guernsey" },
  { code: "324", name: "Guinea" },
  { code: "624", name: "Guinea Bissau" },
  { code: "328", name: "Guyana" },
  { code: "332", name: "Haiti" },
  { code: "334", name: "Heard and McDonald" },
  { code: "340", name: "Honduras" },
  { code: "344", name: "R.O.C. Hong Kong" },
  { code: "348", name: "Hungary" },
  { code: "352", name: "Iceland" },
  { code: "360", name: "Indonesia" },
  { code: "364", name: "Iran" },
  { code: "368", name: "Iraq" },
  { code: "372", name: "Ireland" },
  { code: "833", name: "Isle of Man" },
  { code: "376", name: "Israel" },
  { code: "380", name: "Italy" },
  { code: "388", name: "Jamaica" },
  { code: "392", name: "Japan" },
  { code: "832", name: "Jersey" },
  { code: "396", name: "Johnston Island" },
  { code: "398", name: "Kazakhstan" },
  { code: "404", name: "Kenya" },
  { code: "296", name: "Kiribati" },
  { code: "991", name: "Republic of Kosovo" },
  { code: "417", name: "Kyrgyzstan" },
  { code: "418", name: "Lao" },
  { code: "428", name: "Latvia" },
  { code: "426", name: "Lesotho" },
  { code: "430", name: "Liberia" },
  { code: "434", name: "Libya" },
  { code: "438", name: "Liechtenstein" },
  { code: "440", name: "Lithuania" },
  { code: "442", name: "Luxembourg" },
  { code: "446", name: "R.O.C. Macao" },
  { code: "450", name: "Madagascar" },
  { code: "454", name: "Malawi" },
  { code: "458", name: "Malaysia" },
  { code: "462", name: "Maldives" },
  { code: "466", name: "Mali" },
  { code: "470", name: "Malta" },
  { code: "584", name: "Marshall Islands" },
  { code: "474", name: "Martinique" },
  { code: "478", name: "Mauritania" },
  { code: "480", name: "Mauritius" },
  { code: "175", name: "Mayotte" },
  { code: "484", name: "Mexico" },
  { code: "583", name: "Micronesia" },
  { code: "488", name: "Midway Islands" },
  { code: "498", name: "Moldova" },
  { code: "492", name: "Monaco" },
  { code: "496", name: "Mongolia" },
  { code: "499", name: "Montenegro" },
  { code: "500", name: "Montserrat" },
  { code: "504", name: "Morocco" },
  { code: "508", name: "Mozambique" },
  { code: "104", name: "Myanmar" },
  { code: "516", name: "Namibia" },
  { code: "520", name: "Nauru" },
  { code: "532", name: "Netherlands Antilles" },
  { code: "528", name: "Netherlands" },
  { code: "540", name: "New Caledonia" },
  { code: "554", name: "New Zealand" },
  { code: "558", name: "Nicaragua" },
  { code: "562", name: "Niger" },
  { code: "566", name: "Nigeria" },
  { code: "570", name: "Niue" },
  { code: "000", name: "No Nationality" },
  { code: "574", name: "Norfolk Island" },
  { code: "408", name: "North Korea" },
  { code: "807", name: "North Macedonia" },
  { code: "580", name: "Northern Mariana Islands" },
  { code: "578", name: "Norway" },
  { code: "582", name: "Pacific Islands" },
  { code: "999", name: "Palestine" },
  { code: "585", name: "Palau" },
  { code: "590", name: "Panama" },
  { code: "598", name: "Papua New Guinea" },
  { code: "600", name: "Paraguay" },
  { code: "604", name: "Peru" },
  { code: "612", name: "Pitcairn" },
  { code: "616", name: "Poland" },
  { code: "620", name: "Portugal" },
  { code: "630", name: "Puerto Rico" },
  { code: "101", name: "Qatari Document" },
  { code: "638", name: "Reunion" },
  { code: "642", name: "Romania" },
  { code: "643", name: "Russia" },
  { code: "810", name: "Russia (Historical)" },
  { code: "646", name: "Rwanda" },
  { code: "732", name: "Sahara W" },
  { code: "652", name: "Saint Barthelemy" },
  { code: "654", name: "Saint Helena" },
  { code: "659", name: "Saint Kitts and Nevis" },
  { code: "658", name: "Saint Kitts-Nevis-Anguilla" },
  { code: "662", name: "Saint Lucia" },
  { code: "663", name: "Saint Martin (French part)" },
  { code: "666", name: "Saint Pierre and Miquelon" },
  { code: "670", name: "Saint Vincent & Grenadines" },
  { code: "882", name: "Samoa" },
  { code: "674", name: "San Marino" },
  { code: "678", name: "Sao Tome and Principe" },
  { code: "686", name: "Senegal" },
  { code: "688", name: "Serbia" },
  { code: "891", name: "Serbia and Montenegro" },
  { code: "690", name: "Seychelles" },
  { code: "694", name: "Sierra Leone" },
  { code: "702", name: "Singapore" },
  { code: "703", name: "Slovakia" },
  { code: "705", name: "Slovenia" },
  { code: "090", name: "Solomon Islands" },
  { code: "706", name: "Somalia" },
  { code: "710", name: "South Africa" },
  { code: "410", name: "South Korea" },
  { code: "728", name: "South Sudan" },
  { code: "724", name: "Spain" },
  { code: "144", name: "Sri Lanka" },
  { code: "740", name: "Suriname" },
  { code: "744", name: "Svalbard Jan Mayen" },
  { code: "752", name: "Sweden" },
  { code: "756", name: "Switzerland" },
  { code: "762", name: "Tajikistan" },
  { code: "834", name: "Tanzania" },
  { code: "764", name: "Thailand" },
  { code: "626", name: "Timor Leste" },
  { code: "768", name: "Togo" },
  { code: "772", name: "Tokelau" },
  { code: "776", name: "Tonga" },
  { code: "780", name: "Trinidad and Tobago" },
  { code: "788", name: "Tunisia" },
  { code: "795", name: "Turkmenistan" },
  { code: "796", name: "Turks and Caicos Islands" },
  { code: "798", name: "Tuvalu" },
  { code: "792", name: "Republic of Turkiye" },
  { code: "800", name: "Uganda" },
  { code: "804", name: "Ukraine" },
  { code: "888", name: "United Nations" },
  { code: "858", name: "Uruguay" },
  { code: "860", name: "Uzbekistan" },
  { code: "548", name: "Vanuatu" },
  { code: "336", name: "Vatican" },
  { code: "862", name: "Venezuela" },
  { code: "704", name: "Vietnam" },
  { code: "092", name: "Virgin Islands (British)" },
  { code: "850", name: "Virgin Islands US" },
  { code: "872", name: "Wake Island" },
  { code: "876", name: "Wallis and Futuna" },
  { code: "886", name: "Yemen" },
  { code: "890", name: "Yugoslavia" },
  { code: "894", name: "Zambia" },
  { code: "981", name: "Zanzibar" },
  { code: "716", name: "Zimbabwe" },
];
